from PySide6 import QtCore, QtGui, QtWidgets
from mywidgets import CaptionWidget, MyCheckBox
from lang import tr

class Ui_eq_window(object):
    def setupUi(self, dialog_window):
        dialog_window.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.Tool)
        dialog_window.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        dialog_window.setObjectName("Equalizer")
        dialog_window.resize(352, 188)
        dialog_window.setMinimumSize(QtCore.QSize(0, 120))
        dialog_window.setMaximumSize(QtCore.QSize(16777215, 220))
        dialog_window.setWindowTitle("Equalizer")
        self.dialoglayout = QtWidgets.QVBoxLayout(dialog_window)
        self.dialoglayout.setContentsMargins(14,14,14,14)
        self.dialoglayout.setSpacing(0)
        self.dialoglayout.setObjectName('dialoglayout')
        self.eq_window = QtWidgets.QWidget(dialog_window)
        self.eq_window.setObjectName('eq_window')
        effect = QtWidgets.QGraphicsDropShadowEffect()
        effect.setColor(QtGui.QColor(0, 0, 0, 255))
        effect.setOffset(0)
        effect.setBlurRadius(18)
        self.eq_window.setGraphicsEffect(effect)

        self.dialoglayout.addWidget(self.eq_window)

        self.verticalLayout = QtWidgets.QVBoxLayout(self.eq_window)
        self.verticalLayout.setContentsMargins(6, 2, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_close = QtWidgets.QWidget(self.eq_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_close.sizePolicy().hasHeightForWidth())
        self.w_close.setSizePolicy(sizePolicy)

        self.w_close.setStyleSheet("QWidget#w_close {background: qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0 #36000000 stop:1 #00000000);}")
        self.w_close.setObjectName("w_close")
        self.hl_top = QtWidgets.QHBoxLayout(self.w_close)
        self.hl_top.setContentsMargins(0, 1, 0, 1)
        self.hl_top.setSpacing(4)
        self.hl_top.setObjectName("hl_top")
        self.cbEnable = MyCheckBox(self.w_close)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbEnable.sizePolicy().hasHeightForWidth())
        self.cbEnable.setSizePolicy(sizePolicy)
        self.cbEnable.setObjectName("cbEnable")
        self.cbEnable.setToolTip(tr("tool_tip_enable_eq"))
        self.hl_top.addWidget(self.cbEnable)
        self.l_caption = CaptionWidget(dialog_window, self.w_close)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.l_caption.setFont(font)

        #self.l_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.l_caption.setObjectName("l_caption")
        self.hl_top.addWidget(self.l_caption)

        #self.bSettings = MyLabel({'default': 'QLabel {background: url(":/images/set.png") no-repeat center center } '
        #                                     'QLabel:hover {background:  url(":/images/set_h.png") no-repeat center '
        #                                     'center}'}, self.w_close)
        #self.bSettings.setObjectName("bSettings")
        #self.bSettings.setMinimumSize(QtCore.QSize(18, 18))
        #self.bSettings.setMaximumSize(QtCore.QSize(18, 18))
        #self.bSettings.setText("")
        #self.bSettings.setToolTip(tr("tool_tip_settings_eq"))
        #self.hl_top.addWidget(self.bSettings)
        self.bMenu = QtWidgets.QPushButton(self.w_close)
        self.bMenu.setFlat(True)
        self.bMenu.setObjectName('bMenu')
        self.bMenu.setMinimumSize(QtCore.QSize(18, 18))
        self.bMenu.setMaximumSize(QtCore.QSize(18, 18))
        self.hl_top.addWidget(self.bMenu)
        #spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.hl_top.addItem(spacerItem1)
        self.bClose = QtWidgets.QPushButton(self.w_close)
        self.bClose.setFlat(True)
        self.bClose.setMinimumSize(QtCore.QSize(18, 18))
        self.bClose.setMaximumSize(QtCore.QSize(18, 18))
        self.bClose.setText("")
        self.bClose.setObjectName("bClose")
        self.hl_top.addWidget(self.bClose)
        self.verticalLayout.addWidget(self.w_close)
        self.w_bars = QtWidgets.QWidget(self.eq_window)
        self.w_bars.setMinimumSize(QtCore.QSize(0, 120))
        self.w_bars.setObjectName("w_bars")
        self.verticalLayout.addWidget(self.w_bars)

        self.retranslateUi(dialog_window)
        QtCore.QMetaObject.connectSlotsByName(self.eq_window)

    def retranslateUi(self, dialog_window):
        self.l_caption.caption = tr("equalizer")

import images_rc
