from PySide6 import QtCore, QtWidgets
from lang import tr

FIXED = QtWidgets.QSizePolicy.Fixed
EXPANDED = QtWidgets.QSizePolicy.Expanding
PREFERRED = QtWidgets.QSizePolicy.Preferred


def size_policy(widget, hor, ver):
    sizePolicy = QtWidgets.QSizePolicy(hor, ver)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(widget.sizePolicy().hasHeightForWidth())
    widget.setSizePolicy(sizePolicy)


class Ui_FileDialog(object):
    def setupUi(self, FileDialog):
        FileDialog.setObjectName("FileDialog")
        FileDialog.resize(643, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_lo = QtWidgets.QHBoxLayout()
        self.top_lo.setObjectName("top_lo")
        self.l_look_in = QtWidgets.QLabel(FileDialog)
        self.l_look_in.setMinimumSize(QtCore.QSize(100, 0))
        self.l_look_in.setObjectName("l_look_in")
        self.top_lo.addWidget(self.l_look_in)
        self.cb = QtWidgets.QComboBox(FileDialog)
        size_policy(self.cb, EXPANDED, FIXED)
        self.cb.setObjectName("cb")
        self.top_lo.addWidget(self.cb)
        self.bUp = QtWidgets.QPushButton(FileDialog)
        self.bUp.setMinimumSize(QtCore.QSize(24, 24))
        self.bUp.setMaximumSize(QtCore.QSize(24, 24))
        self.bUp.setFlat(True)
        self.bUp.setText("")
        self.bUp.setObjectName("bUp")
        self.bUp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.top_lo.addWidget(self.bUp)
        self.verticalLayout.addLayout(self.top_lo)
        self.lo_center = QtWidgets.QHBoxLayout()
        self.lo_center.setSpacing(4)
        self.lo_center.setObjectName("lo_center")
        self.lw_places = QtWidgets.QListWidget(FileDialog)
        size_policy(self.lw_places, FIXED, EXPANDED)
        self.lw_places.setMinimumSize(QtCore.QSize(200, 0))
        self.lw_places.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lw_places.setObjectName("lw_places")
        self.lw_places.setIconSize(QtCore.QSize(24, 24))
        self.lo_center.addWidget(self.lw_places)
        self.listWidget = QtWidgets.QListWidget(FileDialog)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setIconSize(QtCore.QSize(24, 24))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lo_center.addWidget(self.listWidget)
        self.verticalLayout.addLayout(self.lo_center)
        self.bottom_widget = QtWidgets.QWidget(FileDialog)
        self.bottom_widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.bottom_widget.setObjectName("bottom_widget")
        self.lo_bottom = QtWidgets.QHBoxLayout(self.bottom_widget)
        self.lo_bottom.setContentsMargins(0, 0, 0, 0)
        self.lo_bottom.setObjectName("lo_bottom")
        self.lo_bottom_grid = QtWidgets.QGridLayout()
        self.lo_bottom_grid.setObjectName("lo_bottom_grid")
        self.l_file_name = QtWidgets.QLabel(self.bottom_widget)
        size_policy(self.l_file_name, FIXED, PREFERRED)
        self.l_file_name.setMinimumSize(QtCore.QSize(100, 0))
        self.l_file_name.setObjectName("l_file_name")
        self.lo_bottom_grid.addWidget(self.l_file_name, 0, 0, 1, 1)
        self.e_file_name = QtWidgets.QLineEdit(self.bottom_widget)
        self.e_file_name.setObjectName("e_file_name")
        self.lo_bottom_grid.addWidget(self.e_file_name, 0, 1, 1, 1)
        self.l_file_type = QtWidgets.QLabel(self.bottom_widget)
        size_policy(self.l_file_type, FIXED, PREFERRED)
        self.l_file_type.setMinimumSize(QtCore.QSize(100, 0))
        self.l_file_type.setObjectName("l_file_type")
        self.lo_bottom_grid.addWidget(self.l_file_type, 1, 0, 1, 1)
        self.cb_file_type = QtWidgets.QComboBox(self.bottom_widget)
        size_policy(self.cb_file_type, EXPANDED, FIXED)
        self.cb_file_type.setObjectName("cb_file_type")
        self.lo_bottom_grid.addWidget(self.cb_file_type, 1, 1, 1, 1)
        self.lo_bottom.addLayout(self.lo_bottom_grid)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.bottom_widget)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 75))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open)
        self.buttonBox.setObjectName("buttonBox")
        self.lo_bottom.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.bottom_widget)

        self.retranslateUi(FileDialog)
        self.buttonBox.accepted.connect(FileDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FileDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FileDialog)

    def retranslateUi(self, FileDialog):
        FileDialog.setWindowTitle(tr("select_file"))
        self.l_look_in.setText(tr("look_in"))
        self.bUp.setToolTip(tr("parent_directory"))
        self.l_file_name.setText(tr("file_name"))
        self.l_file_type.setText(tr("file_type"))
