
from PyQt5 import QtCore, QtGui, QtWidgets
from mywidgets import MyComboBox, MyListView, CaptionWidget, VerSizeWidget, ImageWidget
from viswidget import VisWidget
# from viswidget3 import VisualWidget
from lang import tr


#def labelstyle(images):
#    if len(images) == 1:
#        return 'QLabel {background:  url("'+images[0]+'") no-repeat center center }'
#    elif len(images) == 2:
#        return 'QLabel {background:  url("'+images[0]+'") no-repeat center center } QLabel:hover {background:  url("'+images[1]+'") no-repeat center center}'
#    else: return ''

def create_button(parent, name, layout, size=(24, 24)):
    b = QtWidgets.QPushButton(parent)
    b.setFlat(True)
    b.setMinimumSize(QtCore.QSize(*size))
    b.setMaximumSize(QtCore.QSize(*size))
    b.setText("")
    b.setObjectName(name)
    b.setFocusPolicy(QtCore.Qt.NoFocus)
    if layout is not None:
        layout.addWidget(b)
    return b


def create_player_button(parent, name, geometry):
    b = create_button(parent, name, None, size=(60, 45))
    b.setGeometry(QtCore.QRect(*geometry))
    return b


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 592)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint) # | QtCore.Qt.Tool
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setWindowTitle("AudioPlayer")
        MainWindow.setContentsMargins(14, 14, 14, 14)

        # create central widget and main vertical layout
        effect = QtWidgets.QGraphicsDropShadowEffect()
        effect.setColor(QtGui.QColor(0, 0, 0, 255))
        effect.setOffset(0)
        effect.setBlurRadius(18)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setGraphicsEffect(effect)
        self.central_widget_vlo = QtWidgets.QVBoxLayout(self.centralwidget)
        self.central_widget_vlo.setSpacing(2)
        self.central_widget_vlo.setObjectName("central_widget_vlo")
        self.central_widget_vlo.setContentsMargins(7, 3, 7, 0)

        # top title panel
        self.hl_top = QtWidgets.QHBoxLayout()
        self.hl_top.setContentsMargins(0, 0, 0, 3)
        self.hl_top.setSpacing(6)
        self.hl_top.setObjectName("hl_top")
        self.title_icon = QtWidgets.QLabel(self.centralwidget)
        self.title_icon.setText('')
        self.title_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.title_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.title_icon.setPixmap(QtGui.QPixmap(':/images/headphones.png'))
        self.hl_top.addWidget(self.title_icon)
        self.caption_widget = CaptionWidget(MainWindow, self.centralwidget)
        self.caption_widget.caption = '- - AudioPlayer - -'
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.caption_widget.setFont(font)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(self.caption_widget.sizePolicy().hasHeightForWidth())
        self.hl_top.addWidget(self.caption_widget)
        self.bMin = create_button(self.centralwidget, "bMin", self.hl_top, (18, 18))
        self.bClose = create_button(self.centralwidget, "bClose", self.hl_top, (18, 18))
        self.central_widget_vlo.addLayout(self.hl_top)

        # info layout
        self.w_info = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_info.sizePolicy().hasHeightForWidth())
        self.w_info.setSizePolicy(sizePolicy)
        self.w_info.setMinimumSize(QtCore.QSize(0, 52))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.w_info.setFont(font)
        self.w_info.setObjectName("w_info")
        self.w_info_vlo = QtWidgets.QVBoxLayout(self.w_info)
        self.w_info_vlo.setContentsMargins(4, 4, 4, 4)
        self.w_info_vlo.setSpacing(0)
        self.w_info_vlo.setObjectName("w_info_vlo")
        # image
        self.l_image_hlo = QtWidgets.QHBoxLayout()
        self.l_image_hlo.setContentsMargins(0, 0, 0, 0)
        self.l_image_hlo.setSpacing(0)
        self.l_image_hlo.setObjectName("l_image_hlo")
        self.l_image = ImageWidget(self.w_info)
        self.l_image.setEnabled(True)
        #self.l_image.setAlignment(QtCore.Qt.AlignCenter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_image.sizePolicy().hasHeightForWidth())
        self.l_image.setSizePolicy(sizePolicy)
        #self.l_image.setText("")
        self.l_image.setObjectName("l_image")
        self.l_image.setMinimumSize(QtCore.QSize(180, 180))
        self.l_image.setMaximumSize(QtCore.QSize(180, 180))
        self.l_image_hlo.addWidget(self.l_image)
        #self.w_info_vlo.addWidget(self.l_image)
        self.w_info_vlo.addLayout(self.l_image_hlo)
        self.l_image.setPixmap(QtGui.QPixmap(":/images/logo.png"))

        # l_info music file title
        self.l_info = QtWidgets.QLabel(self.w_info)
        self.l_info.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.l_info.setFont(font)
        self.l_info.setAlignment(QtCore.Qt.AlignCenter)
        self.l_info.setWordWrap(True)
        self.l_info.setObjectName("l_info")
        self.l_info.setText(' ')
        self.w_info_vlo.addWidget(self.l_info)
        # visualization widget
        self.viswidget = VisWidget(self.w_info)
        self.viswidget.setObjectName('viswidget')
        self.viswidget.setMinimumSize(QtCore.QSize(100, 60))
        self.w_info_vlo.addWidget(self.viswidget)
        self.central_widget_vlo.addWidget(self.w_info)

        # track time
        self.track_hlo = QtWidgets.QHBoxLayout()
        self.track_hlo.setSpacing(4)
        self.track_hlo.setObjectName("track_hlo")
        self.l_time = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_time.sizePolicy().hasHeightForWidth())
        # l_time
        self.l_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.l_time.setFont(font)
        self.l_time.setObjectName("l_time")
        self.l_time.setText("00:00")
        self.track_hlo.addWidget(self.l_time)
        # track bar
        self.w_track = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_track.sizePolicy().hasHeightForWidth())
        self.w_track.setSizePolicy(sizePolicy)
        self.w_track.setMinimumSize(QtCore.QSize(0, 16))
        self.w_track.setObjectName("w_track")
        self.track_hlo.addWidget(self.w_track)
        self.r_time = QtWidgets.QLabel(self.centralwidget)
        self.r_time.setText("00.00")
        self.r_time.setObjectName("r_time")
        self.track_hlo.addWidget(self.r_time)
        self.central_widget_vlo.addLayout(self.track_hlo)

        # controls
        self.w_controls = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_controls.sizePolicy().hasHeightForWidth())
        self.w_controls.setSizePolicy(sizePolicy)
        self.w_controls.setMinimumSize(QtCore.QSize(0, 50))
        self.w_controls.setObjectName("w_controls")
        self.w_controls_hlo = QtWidgets.QHBoxLayout(self.w_controls)
        self.w_controls_hlo.setContentsMargins(0, 0, 0, 0)
        self.w_controls_hlo.setSpacing(2)
        self.w_controls_hlo.setObjectName("w_controls_hlo")
        self.btn_panel = QtWidgets.QWidget(self.w_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_panel.sizePolicy().hasHeightForWidth())
        self.btn_panel.setSizePolicy(sizePolicy)
        self.btn_panel.setObjectName("btn_panel")
        self.btn_panel_hlo = QtWidgets.QHBoxLayout(self.btn_panel)
        self.btn_panel_hlo.setContentsMargins(0, 0, 0, 0)
        self.btn_panel_hlo.setSpacing(2)
        self.btn_panel_hlo.setObjectName("btn_panel_hlo")
        self.wButtonContainer = QtWidgets.QWidget(self.btn_panel)
        self.wButtonContainer.setMinimumSize(QtCore.QSize(184, 45))
        self.wButtonContainer.setMaximumSize(QtCore.QSize(184, 45))
        self.wButtonContainer.setObjectName("wButtonContainer")

        self.bPrev = create_player_button(self.wButtonContainer, 'bPrev', (-1, 0, 60, 45))
        self.bPlay = create_player_button(self.wButtonContainer, "bPlay", (41, 0, 60, 45))
        self.bStop = create_player_button(self.wButtonContainer, "bStop", (83, 0, 60, 45))
        self.bNext = create_player_button(self.wButtonContainer, "bNext", (125, 0, 60, 45))

        self.btn_panel_hlo.addWidget(self.wButtonContainer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btn_panel_hlo.addItem(spacerItem)

        self.bLoop = create_button(self.btn_panel, "bLoop", self.btn_panel_hlo, size=(32, 32))
        self.bEq = create_button(self.btn_panel, "bEq", self.btn_panel_hlo, size=(32, 32))
        #self.bPlayList = create_button(self.btn_panel, "bPlaylist", self.btn_panel_hlo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.btn_panel_hlo.addItem(spacerItem1)
        self.w_controls_hlo.addWidget(self.btn_panel)
        self.w_volume = QtWidgets.QWidget(self.w_controls)
        self.w_volume.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_volume.sizePolicy().hasHeightForWidth())
        self.w_volume.setSizePolicy(sizePolicy)
        self.w_volume.setMinimumSize(QtCore.QSize(50, 0))
        self.w_volume.setObjectName("w_volume")
        self.w_controls_hlo.addWidget(self.w_volume)
        self.central_widget_vlo.addWidget(self.w_controls)
        # playlist
        self.hl_plalistselect = QtWidgets.QHBoxLayout()
        self.hl_plalistselect.setSpacing(2)
        self.hl_plalistselect.setObjectName("hl_plalistselect")
        self.comboBox = MyComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.hl_plalistselect.addWidget(self.comboBox)
        self.b_addplaylist = create_button(self.centralwidget, "b_addplaylist", self.hl_plalistselect)
        self.b_editplaylist = create_button(self.centralwidget, "b_editplaylist", self.hl_plalistselect)
        self.b_delplaylist = create_button(self.centralwidget, "b_delplaylist", self.hl_plalistselect)
        self.central_widget_vlo.addLayout(self.hl_plalistselect)

        #listview playlist
        self.listView = MyListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.listView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.listView.setFont(font)
        self.listView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listView.setIconSize(QtCore.QSize(24, 24))
        self.listView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listView.setObjectName("listView")
        self.central_widget_vlo.addWidget(self.listView)
        self.playlist_buttons_hlo = QtWidgets.QHBoxLayout()
        self.playlist_buttons_hlo.setSpacing(10)
        self.playlist_buttons_hlo.setObjectName("playlist_buttons_hlo")
        self.b_addfile = create_button(self.centralwidget, "b_addfile", self.playlist_buttons_hlo)
        self.b_addlink = create_button(self.centralwidget, "b_addlink", self.playlist_buttons_hlo)
        self.b_delfile = create_button(self.centralwidget, "b_delfile", self.playlist_buttons_hlo)
        self.b_clearplaylist = create_button(self.centralwidget, "b_clearplaylist", self.playlist_buttons_hlo)
        self.b_copytoplaylist = create_button(self.centralwidget, "b_copytoplaylist", self.playlist_buttons_hlo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playlist_buttons_hlo.addItem(spacerItem2)
        self.l_version = QtWidgets.QLabel(self.centralwidget)
        self.l_version.setObjectName('l_version')
        self.l_version.setStyleSheet('QLabel#l_version{font-size: 7pt; color: #888;}')
        self.l_version.setText('v. 2.3')
        self.l_version.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight)
        self.playlist_buttons_hlo.addWidget(self.l_version)
        self.central_widget_vlo.addLayout(self.playlist_buttons_hlo)

        #bottom widget for vertical size change
        self.bottom_widget = VerSizeWidget(self.centralwidget)
        self.bottom_widget.setMinimumSize(QtCore.QSize(0, 4))
        self.bottom_widget.setMaximumSize(QtCore.QSize(2048, 4))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.bottom_widget.setSizePolicy(sizePolicy)
        self.bottom_widget.setObjectName('bottom_widget')
        self.bottom_widget.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.central_widget_vlo.addWidget(self.bottom_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.b_addplaylist.setToolTip(tr("add_playlist"))
        self.b_editplaylist.setToolTip(tr("rename_playlist"))
        self.b_delplaylist.setToolTip(tr("remove_playlist"))
        self.b_addfile.setToolTip(tr("add_track_to_playlist"))
        self.b_addlink.setToolTip(tr("add_url_to_playlist"))
        self.b_delfile.setToolTip(tr("remove_track"))
        self.b_clearplaylist.setToolTip(tr("clear_playlist"))
        self.b_copytoplaylist.setToolTip(tr("copy_to_playlist"))

import images_rc
